---


- name: Setup myid
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.data_dir }}/myid"
    src: myid.j2
  notify:
   - restart zookeeper
  tags:
    - zookeeper

- name: Setup zoo.cfg file
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.conf_dir }}/zoo.cfg"
    mode: 0644
    src: zoo.cfg.j2
  notify:
   - restart zookeeper
  tags:
    - zookeeper

- name: Create Zookeeper log4j config
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.conf_dir }}/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Setup Zookeeper environment config
  become: yes
  become_user: "{{ zookeeper.user }}"
  template:
    dest: "{{ zookeeper.conf_dir }}/environment"
    mode: 0644
    src: environment.j2
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Start Zookeeper service
  become: yes
  service:
    name: zookeeper
    state: started
  tags:
    - zookeeper

- name: Flush handlers to ensure Zookeeper is up to date
  meta: flush_handlers
  tags:
    - zookeeper

- name: Wait for Zookeeper port
  wait_for:
    port: "{{ zookeeper.client_port }}"
    state: started
    timeout: 30
  tags:
    - zookeeper
