---

# Needed to ensure some services start properly
- name: Set hostname
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"
  notify:
    - restart kafka
  tags:
    - kafka


- name: Setup environment config
  become: yes
  become_user: "{{ kafka.user }}"
  template:
    dest: "/home/{{ kafka.user }}/etc/environment"
    mode: 0644
    src: environment.j2
  notify:
    - restart kafka
  tags:
    - kafka

- name: Create log4j.properties
  become: yes
  become_user: "{{ kafka.user }}"
  template:
    dest: "/home/{{ kafka.user }}/etc/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart kafka
  tags:
    - kafka

- name: Create server.properties
  become: yes
  become_user: "{{ kafka.user }}"
  template:
    dest: "/home/{{ kafka.user }}/etc/server.properties"
    mode: 0640
    src: server.properties.j2
  notify:
    - restart kafka
  tags:
    - kafka

- name: Ensure Kafka is running
  become: yes
  service:
    name: kafka
    state: started
  tags:
    - kafka

- name: Flush handlers to ensure Kafka is up to date
  meta: flush_handlers
  tags:
    - kafka

- name: Wait for Kafka port
  wait_for:
    port: "{{ kafka.port }}"
    state: started
    timeout: 120
  tags:
    - kafka
