---

users_and_groups:
  # Groups List
  # groups:
  #   - name: mygroup
  #     system: yes
  groups: [ ]

  # Users List
  # users:
  #   - name: my.username
  #     groups:
  #       - wheel
  #       - users
  #
  users: [ ]

  # Sudoers
  # sudoers:
  #   - name: ipsum
  #     user: "%ipsum"
  #     runas: "ALL=(ALL)"
  #     commands: "NOPASSWD: ALL"
  sudoers:
      - name: wheel
        user: "%wheel"
        runas: "ALL=(ALL)"
        commands: "NOPASSWD: ALL"

  # Use this to only allow certain users contextually
  # Note that groups will always be created, but users
  # in groups will only be allowed if they belong to a
  # group in this list
  whitelist_groups: []
