---
zk1_host: 192.168.7.151
zk2_host: 192.168.7.152
zk3_host: 192.168.7.153
user: cloud
user_group: cloud
##python -c 'import crypt; print crypt.crypt("cloud", "$1$SomeSalt$")'
password: $1$SomeSalt$15avH4qSlfRSEvC0bIn2./
