---
- hosts: zookeeper
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  vars:
    - user: zookeeper
    - user_group: zookeeper
    ##python -c 'import crypt; print crypt.crypt("cloud", "$1$SomeSalt$")'
    - password: $1$SomeSalt$15avH4qSlfRSEvC0bIn2./
  roles:
    - common
    - jdk8
    - zookeeper


- hosts: kafka1
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  vars:
    - user: kafka
    - user_group: kafka
    ##python -c 'import crypt; print crypt.crypt("cloud", "$1$SomeSalt$")'
    - password: $1$SomeSalt$15avH4qSlfRSEvC0bIn2./
  roles:
    - common
    - jdk8
    - kafka

- hosts: filebeat
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - common
    - filebeat
