---
# defaults file for filebeat
filebeat_deb_url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.0.0-amd64.deb"
filebeat_config:
  filebeat:
    prospectors:
      - paths:
          - /var/log/messages
          - /var/log/*.log
        input_type: log
  output:
    file:
      path: /tmp/filebeat
      filename: filebeat
  logging:
    to_syslog: true
    level: error
